app/transactions/routes.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from app.users_authentication.models import User
from app.categories.models import Category
from .transaction_db import TransactionsModal
from flask_jwt_extended import (
    verify_jwt_in_request,
    get_jwt_identity,
    jwt_required
)

TransactionsModal.create_transaction_table()

transactions = Blueprint(
    'transactions',
    __name__,
    url_prefix='/transactions',
    static_folder='static',
    template_folder='templates'
)


@transactions.route('/', methods=['GET'])
def transactions_page():
    try:
        verify_jwt_in_request()
    except Exception:
        flash(
            "Sessão expirada. Faça login novamente.",
            category="token_expired"
        )
        return redirect(url_for("users.signin_page"))

    user_id = get_jwt_identity()
    user = User.query.get(user_id)

    transactions_filters = {key: request.args.get(key) for key in [
        'search', 'filter-type', 'filter-category', 'filter-start-date',
        'filter-end-date', 'filter-min-amount', 'filter-max-amount',
        'filter-payment-method']
    }

    category_colors = {
        'Casa': '#F7B7B7',
        'Viagem': '#B2D7F6',
        'Entretenimento': '#F1D7A7',
        'Estudos': '#B7D6B5',
        'Saúde': '#F5D1D1',
        'Mercado': '#D0E5D7'
    }

    transactions_list = TransactionsModal.transactions_get_list(
        transactions_filters, user_id=user_id
    )
    return render_template(
        'transactions_list_page.html',
        user=user,
        transactions=transactions_list,
        transactions_filters=transactions_filters,
        category_colors=category_colors
    )


@transactions.route('/create', methods=['GET', 'POST'])
@jwt_required()
def transaction_create_page():
    user_id = get_jwt_identity()
    if request.method == 'POST':
        try:
            transaction_data = {key: request.form.get(key) for key in [
                'title', 'amount', 'category', 'payment_method', 'description',
                'transaction_date', 'transaction_hour', 'is_recurring',
                'start_date',
                'end_date', 'interval', 'number_of_payments',
                'transaction_type']
            }

            TransactionsModal.transaction_create(
                transaction_data, user_id=user_id
            )

            flash('Criada com sucesso.', category='success')
            return redirect(url_for('transactions.transactions_page'))
        except Exception as e:
            flash(
                'Ocorreu um erro ao criar, tente novamente.',
                category='error'
            )
            print(f"Error: {e}")

    categories = Category.query.all()
    return render_template('transaction_form_page.html', transaction=None, categories=categories)


@transactions.route('/edit/<int:transaction_id>', methods=['GET', 'POST'])
def transaction_edit_page(transaction_id):

    try:
        verify_jwt_in_request()
    except Exception:
        return redirect(url_for("users.signin_page"))

    if request.method == 'GET':
        transaction = TransactionsModal.transactions_get_list(
            transaction_id=transaction_id
        )[0]
        categories = Category.query.all()

    if request.method == 'POST':
        try:
            transaction_data = {key: request.form.get(key) for key in [
                'title', 'amount', 'category', 'payment_method', 'description',
                'transaction_date', 'transaction_hour', 'is_recurring',
                'start_date',
                'end_date', 'interval', 'number_of_payments',
                'transaction_type']
            }
            transaction_data['transaction_id'] = transaction_id

            TransactionsModal.transaction_edit(transaction_data)
            return redirect(url_for('transactions.transactions_page'))
        except Exception as e:
            flash(
                'Ocorreu um erro ao editar, tente novamente.',
                category='error'
            )
            print(f"Error: {e}")

    return render_template(
        'transaction_form_page.html',
        transaction=transaction,
        categories=categories
    )


@transactions.route('/delete/<int:transaction_id>', methods=['GET'])
def transaction_delete(transaction_id):

    try:
        verify_jwt_in_request()
    except Exception:
        return redirect(url_for("users.signin_page"))

    try:
        TransactionsModal.transaction_delete(transaction_id)
    except Exception as e:
        flash('Ocorreu um erro ao deletar', category='error')
        print(f"Error: {e}")

    return redirect(url_for('transactions.transactions_page'))

app/templates/transactions/transaction_form_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minhas Transações</title>
    <link rel="stylesheet" href="{{ url_for('transactions.static', filename='css/transaction_form_page.css') }}">
    <script src="{{ url_for('transactions.static', filename='js/transaction_form_page.js') }}"></script>
</head>

<body>
    <div class="form-content">

        {% if transaction %}
        <form action="{{ url_for('transactions.transaction_edit_page', transaction_id=transaction['transaction_id']) }}"
            method="POST">
            <h1>Sua Transação</h1>
            {% else %}
            <h1>Nova Transação</h1>
            <form action="{{ url_for('transactions.transaction_create_page') }}" method="POST">
                {% endif %}

                <form action="{{ url_for('transactions.transaction_create_page') }}" method="POST">


                    <div class="first-input-row">
                        <div class="title-container">
                            <label for="title">Título</label>
                            <input type="text" id="title" name="title" placeholder="Digite um Título" required
                                value="{{ transaction.title }}" />
                        </div>

                        <div class="payment-method-container">
                            <label for="payment_method">Método de Pagamento</label>
                            <select id="payment_method" name="payment_method" required>
                                <option value="" disabled selected>Selecione uma opção</option>
                                <option value="Debito" {% if transaction.payment_method=='Debito' %} selected {% endif
                                    %}>Débito</option>
                                <option value="Credito" {% if transaction.payment_method=='Credito' %} selected {% endif
                                    %}>Crédito</option>
                                <option value="PIX" {% if transaction.payment_method=='PIX' %} selected {% endif %}>PIX
                                </option>
                                <option value="Boleto" {% if transaction.payment_method=='Boleto' %} selected {% endif
                                    %}>Boleto</option>
                                <option value="Outro" {% if transaction.payment_method=='Outro' %} selected {% endif %}>
                                    Outro</option>
                            </select>
                        </div>
                    </div>


                    <div class="second-input-row">
                        <div class="amount-container">
                            <label for="amount">Valor</label>
                            <input type="text" id="amount" name="amount" placeholder="Digite um Valor"
                                value="{{ transaction.amount }}" required />
                        </div>

                        <div class="date-container">
                            <label for="transaction_date">Data</label>
                            <input type="date" id="transaction_date" name="transaction_date"
                                value="{{ transaction.transaction_date }}" required />
                        </div>

                        <div class="category-container">
                            <label for="category">Categoria</label>
                            <select id="category" name="category" onchange="handleCategoryChange(this)" required>
                                <option value="" disabled selected>Selecione uma opção</option>

                                <optgroup label="Categorias Estáticas">
                                    {% for cat in categorias_estaticas %}
                                    <option value="{{ cat }}" {% if transaction.category==cat %} selected {% endif %}>{{
                                        cat }}</option>
                                    {% endfor %}
                                </optgroup>

                                <optgroup label="Minhas Categorias">
                                    {% for cat in categorias_dinamicas %}
                                    <option value="{{ cat.name }}" data-id="{{ cat.id }}" {% if
                                        transaction.category==cat.name %} selected {% endif %}>
                                        {{ cat.name }}
                                    </option>
                                    {% endfor %}
                                </optgroup>

                                <option value="new">➕ Criar nova categoria...</option>
                            </select>

                            <!-- Área para mostrar ícones de editar/excluir -->
                            <div id="category-actions" style="margin-top: 8px; display: none;">
                                <a id="edit-category-link" class="edit-icon" title="Editar"><i
                                        class="bi bi-pencil-square"></i></a>
                                <a id="delete-category-link" class="delete-icon" title="Excluir"><i
                                        class="bi bi-trash"></i></a>
                            </div>
                        </div>

                    </div>

                    <div class="input-container">
                        <label for="description">Descrição</label>
                        <textarea id="description" name="description"
                            placeholder="Digite uma Descrição para a sua Transação">{{ transaction.description }}</textarea>
                    </div>

                    <div class="is_recurring_content">
                        <div class="left-content">
                            <input type="checkbox" id="checkbox" name="is_recurring" {% if transaction.is_recurring %}
                                checked {% endif %} onchange="toggleNumberOfPayments()">
                            <p class="checkbox_label">Transação Recorrente</p>
                        </div>

                        <div style="display: none;" id="number-of-payments-container">
                            <label for="number_of_payments">Número de parcelas</label>
                            <input type="number" id="number_of_payments" name="number_of_payments"
                                placeholder="Número de parcelas"
                                value="{{ transaction.number_of_payments if transaction.number_of_payments else 2 }}">
                        </div>
                    </div>

                    <!-- <input type="date" id="start_date" name="start_date" value="{{ transaction.start_date }}">

          <input type="date" id="end_date" name="end_date" value="{{ transaction.end_date }}">

          <select id="interval" name="interval">
            <option value="">Selecione um intervalo</option>
            <option value="daily" {% if transaction.interval=='daily' %} selected {% endif %}>Diário</option>
            <option value="weekly" {% if transaction.interval=='weekly' %} selected {% endif %}>Semanal</option>
            <option value="monthly" {% if transaction.interval=='monthly' %} selected {% endif %}>Mensal</option>
            <option value="yearly" {% if transaction.interval=='yearly' %} selected {% endif %}>Anual</option>
          </select> -->

                    <div class="transaction-type-buttons">
                        <button type="button" id="income-btn" class="income-btn"
                            onclick="setTransactionType('income'); changeButtonColor(this)">
                            <i class="bi bi-caret-up-square-fill"></i> Receita
                        </button>
                        <button type="button" id="expense-btn" class="expense-btn"
                            onclick="setTransactionType('expense'); changeButtonColor(this)">
                            <i class="bi bi-caret-down-square-fill"></i> Despesa
                        </button>
                    </div>
                    <input type="hidden" id="transaction_type" name="transaction_type"
                        value="{{ transaction.transaction_type }}">

                    <div class="options-container" {% if not transaction %} style="justify-content: right;" {% endif %}>
                        {% if transaction %}
                        <button type="submit" class="delete-btn">
                            <a
                                href="{{ url_for('transactions.transaction_delete', transaction_id=transaction['transaction_id']) }}">Deletar</a>
                        </button>
                        {% endif %}

                        <div class="right-buttons">
                            <a class="cancel-btn" onclick="window.history.back()">Voltar</a>
                            {% if transaction %}
                            <button type="submit" class="edit-btn">Editar</button>
                            {% else %}
                            <button type="submit" class="submit-btn">Cadastrar</button>
                            {% endif %}
                        </div>
                    </div>

                </form>
    </div>

    <link rel=" stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

</body>

</html>

function handleCategoryChange(select) {
  const selectedOption = select.options[select.selectedIndex];
  const selectedValue = selectedOption.value;

  const actions = document.getElementById("category-actions");
  const editLink = document.getElementById("edit-category-link");
  const deleteLink = document.getElementById("delete-category-link");

  if (selectedValue === "new") {
    window.location.href = "/categories/new";
    return;
  }

  const categoryId = selectedOption.getAttribute("data-id");

  if (categoryId) {
    actions.style.display = "block";
    editLink.href = `/categories/edit/${categoryId}`;
    deleteLink.href = `/categories/delete/${categoryId}`;
  } else {
    actions.style.display = "none";
  }
}